### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by klm122** [DnzJS/BPANN_RelaySelection#1]
Hi,

When trying to execute the training. I get The following error:

Traceback (most recent call last):
  File "nn_relay.py", line 282, in <module>
    nn_local()
  File "nn_relay.py", line 179, in nn_local
    MSE, acc, out_prob_bf, out_prob_predict, op_random, op_bulk, op_persub = v.verify_with_outage_prob(model=model)
  File "/home/akoulali/BPANN_RelaySelection/nn_relay_verify.py", line 89, in verify_with_outage_prob
    G, gn, gidx = util.generate_G()
AttributeError: module 'nn_relay_util' has no attribute 'generate_G'

Ans Indeed, The function generate_G does not exist.

Best regards

**Comment by DnzJS** [comment]
> Hi,
> 
> When trying to execute the training. I get The following error:
> 
> Traceback (most recent call last): File "nn_relay.py", line 282, in nn_local() File "nn_relay.py", line 179, in nn_local MSE, acc, out_prob_bf, out_prob_predict, op_random, op_bulk, op_persub = v.verify_with_outage_prob(model=model) File "/home/akoulali/BPANN_RelaySelection/nn_relay_verify.py", line 89, in verify_with_outage_prob G, gn, gidx = util.generate_G() AttributeError: module 'nn_relay_util' has no attribute 'generate_G'
> 
> Ans Indeed, The function generate_G does not exist.
> 
> Best regards

Sorry for the late reply! We will look into this issue and update in couple days. Thank you for your interest and comments to our work.

Best regards

**Comment by DnzJS** [comment]
> Hi,
> 
> When trying to execute the training. I get The following error:
> 
> Traceback (most recent call last): File "nn_relay.py", line 282, in nn_local() File "nn_relay.py", line 179, in nn_local MSE, acc, out_prob_bf, out_prob_predict, op_random, op_bulk, op_persub = v.verify_with_outage_prob(model=model) File "/home/akoulali/BPANN_RelaySelection/nn_relay_verify.py", line 89, in verify_with_outage_prob G, gn, gidx = util.generate_G() AttributeError: module 'nn_relay_util' has no attribute 'generate_G'
> 
> Ans Indeed, The function generate_G does not exist.
> 
> Best regards

Hi, we've fixed the issue and updated the repo.
